# Config file for automatic testing at travis-ci.org

language: python
sudo: required
dist: trusty

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt -r requirements_dev.txt python-coveralls

# command to run tests, e.g. python setup.py test
script: make coverage

after_success:
    - coveralls
